### ISSUE TITLE
ArgumentOutOfRangeException when te app is installed

### ISSUE THREAD

**Issue by Isatol** [t1m0thyj/WinDynamicDesktop#194]
Submit your bug report or feature request here. If you have questions please ask them on [Gitter](https://gitter.im/t1m0thyj/WinDynamicDesktop) instead.

When reporting a bug please provide:
 - Steps to reproduce it
New installation and then, open it or configuring timing.
First install it was around 9 pm, and everything worked fine. 
But now when i'm reporting this, is 12:30 am.
 - Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/18577289/77728426-18e1a100-6fc2-11ea-9a5d-0b236f9a1217.png)

 - Log file (if it exists, see [here]
(https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) for how to find it)
[2020-03-27 06:25:01.612] System.ArgumentOutOfRangeException: El valor de '27/03/2020 06:00:00 a. m.' no es válido para 'Value'. 'Value' debería estar entre 'MinDate' y 'MaxDate'.
Nombre del parámetro: Value
   en System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
   en WinDynamicDesktop.ScheduleDialog.InputDialog_Load(Object sender, EventArgs e)
   en System.Windows.Forms.Form.OnLoad(EventArgs e)
   en System.Windows.Forms.Form.OnCreateControl()
   en System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   en System.Windows.Forms.Control.CreateControl()
   en System.Windows.Forms.Control.WmShowWindow(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   en System.Windows.Forms.ContainerControl.WndProc(Message& m)
   en System.Windows.Forms.Form.WmShowWindow(Message& m)
   en System.Windows.Forms.Form.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[2020-03-27 06:29:17.674] System.ArgumentOutOfRangeException: El valor de '27/03/2020 06:00:00 a. m.' no es válido para 'Value'. 'Value' debería estar entre 'MinDate' y 'MaxDate'.
Nombre del parámetro: Value
   en System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
   en WinDynamicDesktop.ScheduleDialog.InputDialog_Load(Object sender, EventArgs e)
   en System.Windows.Forms.Form.OnLoad(EventArgs e)
   en System.Windows.Forms.Form.OnCreateControl()
   en System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   en System.Windows.Forms.Control.CreateControl()
   en System.Windows.Forms.Control.WmShowWindow(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   en System.Windows.Forms.ContainerControl.WndProc(Message& m)
   en System.Windows.Forms.Form.WmShowWindow(Message& m)
   en System.Windows.Forms.Form.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

 - Windows version (e.g. 7, 10)
10
 - WinDynamicDesktop version (e.g. 2.0.0)
4.0.0
 - Installation source (e.g. installer, Microsoft Store, portable EXE)
Both versions (Microsoft Store and Exe installer).

**Comment by wangwei8828** [comment]
same issue

**Comment by carlxo** [comment]
I also have the same issue!

--

[2020-04-15 23:20:05.017] System.ArgumentOutOfRangeException: Value of '2020-04-16 06:00:00' is not valid for 'Value'. 'Value' should be between 'MinDate' and 'MaxDate'.
Parameter name: Value
   at System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
   at WinDynamicDesktop.ScheduleDialog.InputDialog_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by iamshilov** [comment]
Same.

![Annotation 2020-04-21 051653](https://user-images.githubusercontent.com/64053730/79818493-a382a980-8390-11ea-8959-02a02ad98541.png)

Appeared right after installation (got my version from Microsoft Store) and now every time after clicking 'Configure Timing…'

[2020-04-21 02:24:33.950] System.ArgumentOutOfRangeException: Значение '21.04.2020 6:00:00' недопустимо для 'Value'. 'Value' должно лежать в диапазоне от 'MinDate' до 'MaxDate'.
Имя параметра: Value
   в System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
   в WinDynamicDesktop.ScheduleDialog.InputDialog_Load(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в System.Windows.Forms.Form.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

When translated it's the same error as above.

**Comment by t1m0thyj** [comment]
This should be fixed in version 4.1.0 which was just released. The update may take 24 hours to show up on Microsoft Store.
