### ISSUE TITLE
Access to the path 'Global\WinDynamicDesktop' is denied

### ISSUE THREAD

**Issue by KingKoolK37** [t1m0thyj/WinDynamicDesktop#240]
Hi,

I love the program, but since yesterday I can't get it to run anymore. Tried a reinstall but it didn't help

[2020-09-07 14:44:14.155] System.UnauthorizedAccessException: Access to the path 'Global\WinDynamicDesktop' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew)
   at WinDynamicDesktop.AppContext.HandleMultiInstance()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

Thanks for your help!

**Comment by t1m0thyj** [comment]
Is this error still happening in the latest version of WDD (4.4.0)?

**Comment by KingKoolK37** [comment]
Hi,

it is running correctly now. Thanks
