### ISSUE TITLE
Error when starting WinDynamicDesktopPortable

### ISSUE THREAD

**Issue by helpme69420** [t1m0thyj/WinDynamicDesktop#252]
**Description**
Everytime I start the program, it says to open the log file. The log file says 
[2020-09-01 11:06:32.230] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at WinDynamicDesktop.LocationIQService.HandleLocationSuccess(LocationIQData data, ScheduleDialog dialog)
   at WinDynamicDesktop.LocationIQService.GetLocationData(String locationStr, ScheduleDialog dialog)
   at WinDynamicDesktop.ScheduleDialog.<okButton_Click>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

[2020-09-01 11:08:49.833] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at WinDynamicDesktop.LocationIQService.HandleLocationSuccess(LocationIQData data, ScheduleDialog dialog)
   at WinDynamicDesktop.LocationIQService.GetLocationData(String locationStr, ScheduleDialog dialog)
   at WinDynamicDesktop.ScheduleDialog.<okButton_Click>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

[2020-09-01 11:09:15.017] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at WinDynamicDesktop.LocationIQService.HandleLocationSuccess(LocationIQData data, ScheduleDialog dialog)
   at WinDynamicDesktop.LocationIQService.GetLocationData(String locationStr, ScheduleDialog dialog)
   at WinDynamicDesktop.ScheduleDialog.<okButton_Click>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

[2020-09-01 11:09:27.307] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at WinDynamicDesktop.LocationIQService.HandleLocationSuccess(LocationIQData data, ScheduleDialog dialog)
   at WinDynamicDesktop.LocationIQService.GetLocationData(String locationStr, ScheduleDialog dialog)
   at WinDynamicDesktop.ScheduleDialog.<okButton_Click>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

[2020-10-05 12:08:42.577] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ThemeLoader.TryLoad(String themeId)
   at WinDynamicDesktop.ThemeManager.LoadInstalledThemes(List`1 themeIds)
   at WinDynamicDesktop.ThemeManager.Initialize()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

[2020-10-05 12:09:28.191] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ThemeLoader.TryLoad(String themeId)
   at WinDynamicDesktop.ThemeManager.LoadInstalledThemes(List`1 themeIds)
   at WinDynamicDesktop.ThemeManager.Initialize()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

[2020-10-05 12:09:40.890] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ThemeLoader.TryLoad(String themeId)
   at WinDynamicDesktop.ThemeManager.LoadInstalledThemes(List`1 themeIds)
   at WinDynamicDesktop.ThemeManager.Initialize()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

[2020-10-05 12:10:39.927] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ThemeLoader.TryLoad(String themeId)
   at WinDynamicDesktop.ThemeManager.LoadInstalledThemes(List`1 themeIds)
   at WinDynamicDesktop.ThemeManager.Initialize()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

**Steps to reproduce**
1. Import an empty json file
2. End task in Task Manager
3. Start WinDynamicDesktopPortable
4. See error.

**Expected behavior**
Show an error message saying that the JSON file was corrupted.

**Environment**
 - OS: Windows 10 1909
 - App version: 4.2.0
 - Installed from: Portable EXE

**Comment by t1m0thyj** [comment]
Changed in https://github.com/t1m0thyj/WinDynamicDesktop/commit/67726f7d9904b17f46ecb02045af893239bca535 to show an error message for empty JSON files. This will be fixed in the next version of WDD.
