### ISSUE TITLE
Limitations of Windows wallpaper APIs

### ISSUE THREAD

**Issue by t1m0thyj** [t1m0thyj/WinDynamicDesktop#321]
* Wallpaper on lock screen
  * [`UserProfilePersonalizationSettings.TrySetLockScreenImageAsync(StorageFile)`](https://docs.microsoft.com/en-us/uwp/api/windows.system.userprofile.userprofilepersonalizationsettings.trysetlockscreenimageasync?view=winrt-20348)
    * Sets lock screen image correctly the first time it is called
    * Fails to update lock screen image afterwards because first image is still cached
    * Known issue: https://stackoverflow.com/questions/56935486#comment100576490_56935486
* Different wallpapers on multiple monitors (planned for next version)
  * [`IDesktopWallpaper::SetWallpaper`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-idesktopwallpaper-setwallpaper)
    * Monitor ID can be specified to set wallpaper on single monitor
    * ~~No fade transition so image change is jarring/unnatural~~
* Different wallpapers on virtual desktops (supported in v4.7.0)
  * ~~[`IVirtualDesktopNotification.CurrentVirtualDesktopChanged`](https://github.com/Grabacr07/VirtualDesktop/blob/master/source/VirtualDesktop/Interop/(interfaces)/IVirtualDesktopNotification.cs#L21)~~
    * ~~Unstable API that broke in Win10 Insiders Preview (https://github.com/Grabacr07/VirtualDesktop/issues/55)~~
    * ~~Need to investigate this when new APIs are exposed (https://github.com/Grabacr07/VirtualDesktop/pull/57)~~

**Comment by rocksdanister** [comment]
@t1m0thyj 
>No fade transition so image change is jarring/unnatural

This depends on Windows `Animate controls and elements' settings

**Comment by t1m0thyj** [comment]
@watermarkhu @7HE-W0R1D Could you please try this build of WDD? It should set the wallpaper across multiple virtual desktops: https://ci.appveyor.com/project/t1m0thyj/windynamicdesktop/builds/39692425/artifacts

**Comment by 7HE-W0R1D** [comment]
Just got some time to try and I installed the UWP version, but it gives me an error when clicking Apply. I've attached the log here.
[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/6690236/WinDynamicDesktop.exe.log)
Seems that the program treats win11 as an unsupported version so it throws that error?

**Comment by watermarkhu** [comment]
@t1m0thyj Setting the same theme across multiple desktops works fine on 21H1 👍

**Comment by 0mri** [comment]
@t1m0thyj got this error when open WDD on new win11 insider preview. 

![InkedScreenshot 2021-06-28 230011_LI](https://user-images.githubusercontent.com/29231457/123697531-b2eb6580-d865-11eb-8809-289cd91e502b.jpg)

[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/6729017/WinDynamicDesktop.exe.log)

**Comment by t1m0thyj** [comment]
I created a new build, could you please try it? I don't know if it'll work on Windows 11, currently the latest version of Windows I have access to test is Windows 10 Insiders (dev edition) and it works there.

**Comment by 7HE-W0R1D** [comment]
> I created a new build, could you please try it? I don't know if it'll work on Windows 11, currently the latest version of Windows I have access to test is Windows 10 Insiders (dev edition) and it works there.

@t1m0thyj yes I can confirm this one works one win 11 ver22000 and all the wallpapers are switching without problems. Thanks for the quick fix!🎉

**Comment by 0mri** [comment]
now it's working, but sometimes i get this error
```
[2021-06-30 16:53:44.125] System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at WinDynamicDesktop.IVirtualDesktopManagerInternal.GetCurrentDesktop(IntPtr hWndOrMon)
   at WinDynamicDesktop.VirtualDesktopApi.SetWallpaper(String imagePath)
   at WinDynamicDesktop.WallpaperChangeScheduler.SetWallpaper(Int32 imageId)
   at WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler(Boolean forceImageUpdate)
   at WinDynamicDesktop.MainMenu.OnRefreshItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by 0mri** [comment]
now it's working, but sometimes i get this error
```
[2021-06-30 16:53:44.125] System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at WinDynamicDesktop.IVirtualDesktopManagerInternal.GetCurrentDesktop(IntPtr hWndOrMon)
   at WinDynamicDesktop.VirtualDesktopApi.SetWallpaper(String imagePath)
   at WinDynamicDesktop.WallpaperChangeScheduler.SetWallpaper(Int32 imageId)
   at WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler(Boolean forceImageUpdate)
   at WinDynamicDesktop.MainMenu.OnRefreshItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by t1m0thyj** [comment]
@0mri Please try again, it should be fixed now: https://ci.appveyor.com/project/t1m0thyj/windynamicdesktop/builds/39839450/artifacts

**Comment by 0mri** [comment]
@t1m0thyj  now i get this error only on scheduled wallpaper change
```
[2021-07-02 16:52:40.591] System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at WinDynamicDesktop.IVirtualDesktopManagerInternal.GetCurrentDesktop(IntPtr hWndOrMon)
   at WinDynamicDesktop.VirtualDesktopApi.SetWallpaper(String imagePath)
   at WinDynamicDesktop.WallpaperApi.<>c__DisplayClass4_0.<SetWallpaper>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by t1m0thyj** [comment]
@0mri I now have access to Win11 and think the issue is fixed, could you please try https://ci.appveyor.com/project/t1m0thyj/windynamicdesktop/builds/39873093/artifacts

**Comment by NyaMisty** [comment]
@t1m0thyj Hi I found this issue from @Grabrcr07's repo.

Windows have been changing interface every half year now, so I strongly suggest that we move to a newer repo like @mntone's instead of manually maintaining those internal interfaces. 

And also, @mntone's repo have already added wallpaper support.

**Comment by t1m0thyj** [comment]
@NyaMisty I agree that manually maintaining the internal interfaces is not ideal. Before doing so I attempted to use @mntone's repo, but found that it doesn't work in a Microsoft Store app because it has to compile a DLL the first time it runs on your machine. If there's a way to work around this, I'm definitely open to using the latest fork of the VirtualDesktop package.

**Comment by t1m0thyj** [comment]
These 3 features have been implemented in WDD v5.
