### ISSUE TITLE
Crash Caused by Object reference not set to an instance of an object on Program Launch

### ISSUE THREAD

**Issue by TheMCSpacePro** [t1m0thyj/WinDynamicDesktop#345]
- WDD Version: 4.6.0
- OS Version: Windows 10 Home, OS Build 21390.2025

Steps to Reproduce:
(The crash happens when the program launches, so there are no reproducion steps)

Are you using the Microsoft Store version of WDD?: Yes

The Crash Report:
[2021-06-21 13:13:38.092] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ConfigMigrator.UpdateToVersion4()
   at WinDynamicDesktop.JsonConfig.LoadConfig()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

**Comment by t1m0thyj** [comment]
There should be a debug.log file in the WDD folder, please upload it to provide more details about the error. See [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) if you're unsure where the WDD folder is.

**Comment by TheMCSpacePro** [comment]
https://pastebin.com/g6r04k0h

**Comment by TheMCSpacePro** [comment]
Must have been an error with the “settings.json” file, since deleting it allowed the program to launch.
