### ISSUE TITLE
Error when opening up.

### ISSUE THREAD

**Issue by TechStudent11** [t1m0thyj/WinDynamicDesktop#364]
- WDD Version: 4.7.0
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Open WinDynamicDesktop

Are you using the Microsoft Store version of WDD?: No

I'll just explain what's happening down here:
I've been using WinDynamicDesktop for a while now. I have WinDynamicDesktop to startup when my computer starts. For some odd reason, every time I launch it, automatically or not, it gives me an error.

See screenshot below:
![image](https://user-images.githubusercontent.com/76978184/131534597-b5a0a214-330b-4478-bd3c-504c844c6a94.png)

If I check the log file, there is one common thing:
```
[2021-08-31 15:44:16.791] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ConfigMigrator.UpdateToVersion4()
   at WinDynamicDesktop.JsonConfig.LoadConfig()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)
```

This is the entire file, just copied and pasted a few times.
Here is the entire log file:
```
[2021-08-30 13:53:05.415] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ConfigMigrator.UpdateToVersion4()
   at WinDynamicDesktop.JsonConfig.LoadConfig()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

[2021-08-30 15:46:07.977] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ConfigMigrator.UpdateToVersion4()
   at WinDynamicDesktop.JsonConfig.LoadConfig()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

[2021-08-30 16:29:37.705] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ConfigMigrator.UpdateToVersion4()
   at WinDynamicDesktop.JsonConfig.LoadConfig()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

[2021-08-31 15:24:33.234] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ConfigMigrator.UpdateToVersion4()
   at WinDynamicDesktop.JsonConfig.LoadConfig()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

[2021-08-31 15:44:16.791] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ConfigMigrator.UpdateToVersion4()
   at WinDynamicDesktop.JsonConfig.LoadConfig()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)
```
Can someone please tell me what is going on? I've tried uninstalling it and reinstalling it but it doesn't work.

**Comment by TechStudent11** [comment]
@t1m0thyj It has been a month and I still get the error!

**Comment by TechStudent11** [comment]
@t1m0thyj I now get this error every time I boot up my PC. I am running Windows 11 btw, but as apparent in the screenshot, running it in Windows 10 didn't change anything.

**Comment by t1m0thyj** [comment]
This error is caused by an old config file from WDD v3, which should automatically get converted to the new v4 format, but for some reason the conversion process is failing.

If you delete the settings.json or settings.conf file in the [WDD app folder](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed), this should hopefully resolve the error, although you'll have to reconfigure your WDD settings like location and theme.

Also, could you please send the contents of debug.log if present in the WDD folder? That should help me to know what caused the error to be able to fix it for other users.

**Comment by TechStudent11** [comment]
@t1m0thyj Okay. The `debug.log` file has been attached. Removing the `settings.json` file worked! Thanks for the help!

Files Attached:
[debug.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/7574608/debug.log)
