### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by tolunayozturk** [t1m0thyj/WinDynamicDesktop#39]
I got this exception error out of nowhere at around 10.30 PM.

![image](https://user-images.githubusercontent.com/15181007/42595391-cb5b479a-855a-11e8-9747-02af7dd9831b.png)

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentOutOfRangeException: Value '0' is not a valid value for Interval. Interval must be greater than 0.
> Parameter name: Interval
>    at System.Windows.Forms.Timer.set_Interval(Int32 value)
>    at WinDynamicDesktop.WallpaperChangeScheduler.StartTimer(Int64 tickInterval)
>    at WinDynamicDesktop.WallpaperChangeScheduler.UpdateNightImage()
>    at WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler(Boolean forceRefresh)
>    at WinDynamicDesktop.WallpaperChangeScheduler.OnWallpaperTimerTick(Object sender, EventArgs e)
>    at System.Windows.Forms.Timer.OnTick(EventArgs e)
>    at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> WinDynamicDesktop
>     Assembly Version: 1.3.1.0
>     Win32 Version: 1.3.1.0
>     CodeBase: file:///C:/Program%20Files/WindowsApps/38719TimothyJohnson.WinDynamicDesktop_1.3.1.0_neutral__rfarkse4rn21a/WinDynamicDesktop/WinDynamicDesktop.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> DesktopBridge.Helpers
>     Assembly Version: 1.1.0.0
>     Win32 Version: 1.1.0.0
>     CodeBase: file:///C:/Program%20Files/WindowsApps/38719TimothyJohnson.WinDynamicDesktop_1.3.1.0_neutral__rfarkse4rn21a/WinDynamicDesktop/DesktopBridge.Helpers.DLL
> ----------------------------------------
> Windows.Storage
>     Assembly Version: 255.255.255.255
>     Win32 Version: 10.0.10011.16384
>     CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.Storage.winmd
> ----------------------------------------
> Windows.Foundation
>     Assembly Version: 255.255.255.255
>     Win32 Version: 10.0.10011.16384
>     CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.Foundation.winmd
> ----------------------------------------
> System.Runtime.InteropServices.WindowsRuntime
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
> ----------------------------------------
> System.Runtime
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 11.0.0.0
>     Win32 Version: 11.0.2.21924
>     CodeBase: file:///C:/Program%20Files/WindowsApps/38719TimothyJohnson.WinDynamicDesktop_1.3.1.0_neutral__rfarkse4rn21a/WinDynamicDesktop/Newtonsoft.Json.DLL
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3120.0 built by: NET472REL1LAST
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Windows.ApplicationModel
>     Assembly Version: 255.255.255.255
>     Win32 Version: 10.0.10011.16384
>     CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.ApplicationModel.winmd
> ----------------------------------------
> System.Runtime.WindowsRuntime
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.WindowsRuntime/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.WindowsRuntime.dll
> ----------------------------------------
> Innovative.SolarCalculator
>     Assembly Version: 2.0.2.0
>     Win32 Version: 2.0.2.0
>     CodeBase: file:///C:/Program%20Files/WindowsApps/38719TimothyJohnson.WinDynamicDesktop_1.3.1.0_neutral__rfarkse4rn21a/WinDynamicDesktop/Innovative.SolarCalculator.DLL
> ----------------------------------------
> Innovative.Geometry.Angle
>     Assembly Version: 2.0.0.0
>     Win32 Version: 2.0.0.0
>     CodeBase: file:///C:/Program%20Files/WindowsApps/38719TimothyJohnson.WinDynamicDesktop_1.3.1.0_neutral__rfarkse4rn21a/WinDynamicDesktop/Innovative.Geometry.Angle.DLL
> ----------------------------------------
> System.Runtime.Extensions
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

**Comment by tolunayozturk** [comment]
Got this error again around 8.30 PM.

**Comment by t1m0thyj** [comment]
This should be fixed in the next version, which I hope to release tomorrow. However, if you're using the Windows Store version then the update won't show up until it's been approved by Microsoft.

**Comment by t1m0thyj** [comment]
Fixed in version 1.4, will close this issue once the update shows up on the Windows Store.
