### ISSUE TITLE
[Bug] System.Runtime.InteropServices.COMException (0x80040154)

### ISSUE THREAD

**Issue by pc-v2** [t1m0thyj/WinDynamicDesktop#424]
- WDD Version: 5.0.1
- OS Version: Windows 11 22581.200

Settings File

```
{
  "locationMode": 1,
  "location": null,
  "latitude": ,
  "longitude": ,
  "sunriseTime": null,
  "sunsetTime": null,
  "sunriseSunsetDuration": 0,
  "activeThemes": [
    null,
    "Big_Sur",
    "Catalina"
  ],
  "darkMode": false,
  "changeLockScreen": true,
  "enableShuffle": false,
  "lastShuffleDate": "04/04/2022 17:00:44",
  "shuffleHistory": [
    "Big_Sur",
    "Catalina"
  ],
  "favoriteThemes": null,
  "language": "en",
  "autoUpdateCheck": true,
  "lastUpdateCheckTime": "04/02/2022 12:06:05",
  "hideTrayIcon": false,
  "fullScreenPause": false,
  "enableScripts": true
}
```

Are you using the Microsoft Store version of WDD?: No
log
```
[2022-04-04 11:14:24.731] System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinDynamicDesktop.COM.DesktopWallpaperFactory.Create()
   at WinDynamicDesktop.WallpaperApi.SetWallpaper(String imagePath, Int32 displayIndex)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Threading.SynchronizationContext.<>c.<Post>b__8_0(ValueTuple`2 s)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


```

**Comment by t1m0thyj** [comment]
Does this issue still happen in the latest version of WDD ([v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0))?
