### ISSUE TITLE
Windows 11 , Does not apply theme

### ISSUE THREAD

**Issue by saivishalkumar** [t1m0thyj/WinDynamicDesktop#431]
- WDD Version: 5.0.1 UWP
- OS Version: Windows 11

Steps to Reproduce:

1. Select a theme
2. Apply Wallpaper

Are you using the Microsoft Store version of WDD?: Yes/No
Yes

**Comment by saivishalkumar** [comment]
[2022-04-13 04:52:35.449] System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at WinDynamicDesktop.UwpHelper.SetWallpaper(String imagePath, Int32 displayIndex)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

[2022-04-13 04:52:41.342] System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at WinDynamicDesktop.UwpHelper.SetWallpaper(String imagePath, Int32 displayIndex)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

[2022-04-13 05:11:52.583] System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at WinDynamicDesktop.UwpHelper.SetWallpaper(String imagePath, Int32 displayIndex)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by t1m0thyj** [comment]
Does this issue still happen in the latest version of WDD ([v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0))?

**Comment by saivishalkumar** [comment]
The issue is resolved. Thank you Tim!

From: Timothy Johnson ***@***.***>
Sent: 30 August 2022 02:13
To: t1m0thyj/WinDynamicDesktop ***@***.***>
Cc: Sai Vishal Kumar Pilla ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [t1m0thyj/WinDynamicDesktop] Windows 11 , Does not apply theme (Issue #431)


Closed #431<https://urldefense.com/v3/__https:/github.com/t1m0thyj/WinDynamicDesktop/issues/431__;!!ACWV5N9M2RV99hQ!K0mHGjsn2ATATLUgdonjpdyBeLHW4PItNCOlHu23_htbHGbtsAxLbA7gh1H_IMKIXoZT19dsKG6ZVJ5gejawbbR_7UFeN2MWBkA$> as completed.
