### ISSUE TITLE
[Bug] Doesn't work with system time locale formats

### ISSUE THREAD

**Issue by swoy45** [t1m0thyj/WinDynamicDesktop#432]
- WDD Version: 5.0.1
- OS Version: Windows 11 22593.1

Steps to Reproduce:

1. Set regional format in system to Japanese
2. Set AM/PM marks in Japanese
3. 'Error occurred. See the logfile...'

Are you using the Microsoft Store version of WDD?: No

Log contents:
```
[2022-04-16 10:53:47.376] System.FormatException: The string '午前 6:00:00' was not recognized as a valid DateTime. There is an unknown word starting at index '0'.
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at WinDynamicDesktop.SunriseSunsetService.GetUserProvidedSolarData(DateTime date)
   at WinDynamicDesktop.SunriseSunsetService.GetSolarData(DateTime date)
   at WinDynamicDesktop.WPF.ThemePreviewerViewModel.PreviewTheme(ThemeConfig theme)
   at WinDynamicDesktop.ThemeDialog.UpdateSelectedItem()
   at WinDynamicDesktop.ThemeDialog.listView1_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by t1m0thyj** [comment]
This should be fixed in 5.0.2. You may have to manually delete the "sunriseTime" and "sunsetTime" lines in the `settings.json` file and then reconfigure them in the Configure Schedule dialog.
