### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by MahanDarabix** [t1m0thyj/WinDynamicDesktop#446]
- WDD Version:5.0.2
- OS Version:Windows 11 212H (build 22000.708)

This message is displayed when I start the program:
Errors occurred

See the logfile 'C:\Users\user name\AppData\Local\Packages\38719TimothyJohnson. WinD ynamicDesktop_rfarkse4rn21a\LocalState\WinDynamicDeskto p.dll.log for details

And it shows this message when I go to that place:
[2022-05-27 13:43:17.852] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.ThemeDialog.<>c.<ThemeDialog_Load>b__13_3(KeyValuePair`2 x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.LazyToArray()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at WinDynamicDesktop.ThemeDialog.ThemeDialog_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

and in debug i see:
//06/03/1401 06:13:17 ب.ظ
./settings.json
{
  "locationMode": 1,
  "location": null,
  "latitude": 36.0,
  "longitude": 51.0,
  "sunriseTime": null,
  "sunsetTime": null,
  "sunriseSunsetDuration": 0,
  "activeThemes": null,
  "darkMode": false,
  "changeLockScreen": false,
  "enableShuffle": false,
  "lastShuffleDate": null,
  "shuffleHistory": null,
  "favoriteThemes": null,
  "language": "en",
  "autoUpdateCheck": true,
  "lastUpdateCheckTime": "05/27/2022 18:13:16",
  "hideTrayIcon": false,
  "fullScreenPause": false,
  "enableScripts": false
}

Thank you so much for your program working so far, can you help it work again?

Are you using the Microsoft Store version of WDD?: Yes
Both the Microsoft version and the GitHub version
In both of them he gave this error

**Comment by MahanDarabix** [comment]
But I forgot to say that the program worked with lower versions, but this morning, after updating to version 5.0.2 through the Microsoft Store, it crashed and gave an error message.
I am currently using your program with version 4.0.0.
I love your app!

**Comment by t1m0thyj** [comment]
Hello, could you please try a test build from here to see if resolves the issue? https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/2400167665

To download/install a test build, scroll down to the Artifacts section of the linked page and download the EXE for your platform. Then run WDD using the downloaded EXE (you can copy it to the folder where WDD is installed, see [here](https://github.com/t1m0thyj/WinDynamicDesktop/wiki/Troubleshooting#finding-where-app-is-installed) if unsure where that is).

**Comment by MahanDarabix** [comment]
It is unique, it works well with test build.
Thank you!
Should I use the same version test build or wait for the next updates of the main program?

**Comment by t1m0thyj** [comment]
Released the fix as 5.3.0.
