### ISSUE TITLE
Update check exception

### ISSUE THREAD

**Issue by MnemonicWME** [t1m0thyj/WinDynamicDesktop#45]
Hello, upon waking the computer from hibernation, I got the following exception:

`
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at WinDynamicDesktop.UpdateChecker.IsUpdateAvailable(String currentVersion, String latestVersion)
   at WinDynamicDesktop.UpdateChecker.CheckAuto()
   at WinDynamicDesktop.UpdateChecker.TryCheckAuto()
   at WinDynamicDesktop.WallpaperChangeScheduler.OnWallpaperTimerTick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

I suppose the internet connection wasn't fully restored yet and GetLatestVersion returned null.

**Comment by t1m0thyj** [comment]
Thanks for finding this, I'm planning to release an update with several bug fixes this week including this one.

**Comment by t1m0thyj** [comment]
Should be fixed in version 1.4.1 which was just released, sorry for the delay.
