### ISSUE TITLE
WinDynamicDestop Crashes While Asking Timezone

### ISSUE THREAD

**Issue by Rajbir98** [t1m0thyj/WinDynamicDesktop#455]
- WDD Version: 5.0.3
- OS Version: Windows 7

Steps to Reproduce:

1. Install WDD
2. Launch WDD
3. WDD Crashes

Are you using the Microsoft Store version of WDD?: No

**log**

```
[2022-06-18 08:26:53.847] System.EntryPointNotFoundException: Entry point was not found.
   at WinRT.Platform.CoDecrementMTAUsage(IntPtr cookie)
   at WinRT.WinrtModule.Finalize()
```
**settings.json**

```
{
  "locationMode": 0,
  "location": null,
  "latitude": null,
  "longitude": null,
  "sunriseTime": null,
  "sunsetTime": null,
  "sunriseSunsetDuration": 0,
  "activeThemes": null,
  "darkMode": false,
  "changeLockScreen": false,
  "enableShuffle": false,
  "lastShuffleDate": null,
  "shuffleHistory": null,
  "favoriteThemes": null,
  "language": "en",
  "autoUpdateCheck": true,
  "lastUpdateCheckTime": "06/18/2022 13:54:59",
  "hideTrayIcon": false,
  "fullScreenPause": false,
  "enableScripts": false
}
```

I think fixing the settings.json can fix the problem

**Comment by t1m0thyj** [comment]
Does this issue still happen in the latest version of WDD ([v5.1.0](https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0))?
