### ISSUE TITLE
WDD crashes from startup

### ISSUE THREAD

**Issue by CarbonConfetti** [t1m0thyj/WinDynamicDesktop#461]
[2022-07-09 00:45:09.245] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.WallpaperEngine.RunScheduler(Boolean forceImageUpdate)
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

- WDD Version: 5.0.3
- OS Version: Windows 11 Home ver 10.0.22000 Build 22000

Steps to Reproduce:

1.Open the exe file
2.That's it

Are you using the Microsoft Store version of WDD?: Yes/No
No
![image](https://user-images.githubusercontent.com/100007189/178085451-e9e5c96a-f6e4-4718-b03b-4ae8977fec13.png)
![image](https://user-images.githubusercontent.com/100007189/178085479-8812a73f-0a45-4814-bea4-9d19d7651508.png)

**Comment by CarbonConfetti** [comment]
Nvm, I just reinstalled and it worked, sorry for bothering you.
