### ISSUE TITLE
Can not open WDD occasionally.

### ISSUE THREAD

**Issue by Skywings96** [t1m0thyj/WinDynamicDesktop#479]
- WDD Version: 5.1.0
- OS Version: Windows 11 22H2  build 22621.521

**When I try to open the WDD, an error message appears, and the app closes automatically. I must open it again and it can work normally. The detail of this  error is as follow:**

> [2022-09-22 06:56:38.108] System.DllNotFoundException: Dll was not found.
>    at MS.Internal.WindowsBase.NativeMethodsSetLastError.SetWindowLongWndProc(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
>    at MS.Win32.UnsafeNativeMethods.CriticalSetWindowLong(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
>    at MS.Win32.HwndSubclass.HookWindowProc(IntPtr hwnd, WndProc newWndProc, IntPtr oldWndProc)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
> 
> [2022-09-23 08:03:51.033] System.DllNotFoundException: Dll was not found.
>    at MS.Internal.WindowsBase.NativeMethodsSetLastError.SetWindowLongWndProc(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
>    at MS.Win32.UnsafeNativeMethods.CriticalSetWindowLong(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
>    at MS.Win32.HwndSubclass.HookWindowProc(IntPtr hwnd, WndProc newWndProc, IntPtr oldWndProc)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
> 
It is worth noting that I didn't see this error before I updated the Windows 11 22H2, and this error happened on my two PC after I updated both of them.
 

Are you using the Microsoft Store version of WDD?: Yes

**Comment by leostudiooo** [comment]
```
[2023-02-19 02:11:35.698] System.NullReferenceException: Object reference not set to an instance of an object.
   at WinDynamicDesktop.ConfigMigrator.UpdateToVersion4()
   at WinDynamicDesktop.ConfigMigrator.Run()
   at WinDynamicDesktop.JsonConfig.LoadConfig()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)
```
As is mentioned in #509 it seems to be a random problem. See, everyone's got different error outputs. I guess it may be a bug of Windows 11 or something like that.

**Comment by t1m0thyj** [comment]
@leostudiooo What version of WinDD do you have installed? I believe the `ConfigMigrator` error was fixed in v5.2.1.

**Comment by leostudiooo** [comment]
![image](https://user-images.githubusercontent.com/35419343/221366350-6ea3a58f-f010-4f87-a764-f6022651dd6e.png)
Having the issue on 5.2.1. (Latest release 5 days ago)

**Comment by leostudiooo** [comment]
I don't really know what is all this about. Tried reinstalling the latest release and even building from source but the same error just repeated.

**Comment by Art-go** [comment]
@leostudiooo i had same issue. Try delete settings.json file at wdd folder. For me it worked.

**Comment by t1m0thyj** [comment]
@Skywings96 Does this issue still happen with the latest version of WinDD (5.3.1)?

**Comment by t1m0thyj** [comment]
The original error reported of "DLL not found" seems to have been caused by Windows Storage Sense deleting DLLs from a temp folder that WinDD relies on and has been fixed in WinDD 5.6.1.
