### ISSUE TITLE
errors after startup windynamic desktop

### ISSUE THREAD

**Issue by rtmburg** [t1m0thyj/WinDynamicDesktop#486]
- WDD Version: 5.1.0
- OS Version: Windows 11 pro 22H2 (build 22621.521)

Steps to Reproduce:

1. Start windows
2. Then pop up appears with following message: 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/115091137/194080826-35fb1b2c-171c-45ee-b1aa-50fe46c83c4b.png">

Error in logfile is:
[2022-10-05 14:06:19.853] System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at WinDynamicDesktop.COM.IDesktopWallpaper.GetMonitorDevicePathAt(UInt32 monitorIndex)
   at WinDynamicDesktop.WallpaperApi.SetWallpaper(String imagePath, Int32 displayIndex)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

This happens regularly, but not all the time.

Are you using the Microsoft Store version of WDD?: Yes

I hope anyone can help. I love the program.

**Comment by rtmburg** [comment]
Problem still persists. Anybody who can help?

**Comment by t1m0thyj** [comment]
Do you still see this error in the latest version of WinDD? Since version 5.4.2, errors setting the wallpaper are handled more gracefully - they still show a warning but should no longer crash the app.

**Comment by codemaster2837** [comment]
I can confirm the error. The problem occurs when I use different wallpapers on different displays. Previously it worked fine for a few days. Later I realised that the monitor name in the drop-down list does not match the monitor to which the wallpaper was assigned. After a restart, the problem described above now occurs. One guess: Is it possible that the monitor list is out of date? I changed my configuration 2 days ago.

**Comment by codemaster2837** [comment]
Is there a solution to this problem? WinDD has been working fine for the last few weeks, but now the problem has returned. 
Here is the excerpt from the error log:
```
[2024-04-26 06:25:02.717] System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at WinDynamicDesktop.COM.IDesktopWallpaper.GetMonitorDevicePathAt(UInt32 monitorIndex)
   at WinDynamicDesktop.WallpaperApi.SetWallpaper(String imagePath, Int32 displayIndex)
   at WinDynamicDesktop.UwpHelper.SetWallpaper(String imagePath, Int32 displayIndex)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```
