### ISSUE TITLE
START ON BOOT ERROR

### ISSUE THREAD

**Issue by bastefps** [t1m0thyj/WinDynamicDesktop#490]
Can't start WDD on boot. coming up with this error when I select start on boot

- WDD Version: 5.1.0
- OS Version: Win 10

[2022-11-06 05:22:41.127] System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.InternalOpenSubKeyCore(String name, Boolean writable)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at WinDynamicDesktop.DesktopHelper.ToggleStartOnBoot()
   at WinDynamicDesktop.MainMenu.OnStartOnBootClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Are you using the Microsoft Store version of WDD?: No

**Comment by direrFlood** [comment]
yes same. fixed this issue by uninstalling regular version and installing store version also disable task schedule start up on login(if u got it installed at first place)
