### ISSUE TITLE
all ios 13 themes and licancabur making errors 

### ISSUE THREAD

**Issue by silentwar-resident** [t1m0thyj/WinDynamicDesktop#529]
**- WDD Version:** 5.3.1
**- OS Version:** windows 11

**Steps to Reproduce:**

**1.** installed all ios 13 themes and got an error  as shown: [https://prnt.sc/RVqyVW92GHY_](https://prnt.sc/RVqyVW92GHY_)

**see log snippet:**

[2023-06-25 03:02:14.791] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at WinDynamicDesktop.WPF.ThemePreviewerViewModel.Start(Int32 index)
   at WinDynamicDesktop.WPF.ThemePreviewerViewModel.PreviewTheme(ThemeConfig theme)
   at System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

 **(same logged errors for all of them in subject of the problem.)**

**Are you using the Microsoft Store version of WDD?: Yes/No**

no.

**Comment by t1m0thyj** [comment]
Fixed in WinDD 5.4.0
