### ISSUE TITLE
Random crashes opening "Select theme"

### ISSUE THREAD

**Issue by Hexaae** [t1m0thyj/WinDynamicDesktop#558]
- WDD Version: 5.3.1
- OS Version: Win11 23H2 build 22631.3007

Steps to Reproduce:
Random issue. I usually put my laptop on sleep every day (i.e. won't do a warm/cold reboot for many days and use Sleep mode instead).
1. RMB over tray WDD icon, and choose "Select theme..."
Will randomly crash with errors like these:

WIN ERRORS:
```
Percorso dell'applicazione che ha generato l'errore:	C:\Users\Luca\Util\WinDynamicDesktop\WinDynamicDesktop.exe

Firma del problema
Nome evento problema:	APPCRASH
Nome applicazione:	WinDynamicDesktop.exe
Versione applicazione:	5.3.1.0
Timestamp applicazione:	641cea1e
Nome modulo con errori:	KERNELBASE.dll
Versione modulo con errori:	10.0.22621.2792
Timestamp modulo con errori:	3091b6fb
Codice eccezione:	e0434352
Offset eccezione:	000000000006567c
Versione SO:	10.0.22631.2.0.0.256.48
ID impostazioni locali:	1040
Informazioni aggiuntive 1:	035c
Ulteriori informazioni 2:	035c53f04602bbd639d421592ac05c18
Ulteriori informazioni 3:	0919
Ulteriori informazioni 4:	09191312e1fcb81407e27e89d28b06f5

-

Percorso dell'applicazione che ha generato l'errore:	C:\Users\Luca\Util\WinDynamicDesktop\WinDynamicDesktop.exe

Firma del problema
Nome evento problema:	APPCRASH
Nome applicazione:	WinDynamicDesktop.exe
Versione applicazione:	5.3.1.0
Timestamp applicazione:	641cea1e
Nome modulo con errori:	KERNELBASE.dll
Versione modulo con errori:	10.0.22621.2792
Timestamp modulo con errori:	3091b6fb
Codice eccezione:	c000041d
Offset eccezione:	000000000006567c
Versione SO:	10.0.22631.2.0.0.256.48
ID impostazioni locali:	1040
Informazioni aggiuntive 1:	3c25
Ulteriori informazioni 2:	3c25064817bb5696ee8af6ada0f190ce
Ulteriori informazioni 3:	b151
Ulteriori informazioni 4:	b151b7dfdea6f19c9bb7126bc7121c8d
```

LOG:
```
[2023-12-28 08:37:32.987] System.DllNotFoundException: Dll was not found.
   at MS.Internal.WindowsBase.NativeMethodsSetLastError.SetWindowLongPtrWndProc(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
   at MS.Win32.UnsafeNativeMethods.CriticalSetWindowLong(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
   at MS.Win32.HwndSubclass.HookWindowProc(IntPtr hwnd, WndProc newWndProc, IntPtr oldWndProc)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

[2023-12-28 20:51:21.242] System.TypeInitializationException: The type initializer for 'WinDynamicDesktop.AppContext' threw an exception.
 ---> System.Runtime.InteropServices.ExternalException (0x80004005): Failed to create system events window thread.
   at Microsoft.Win32.SystemEvents.EnsureSystemEvents(Boolean requireHandle)
   at Microsoft.Win32.SystemEvents.add_PowerModeChanged(PowerModeChangedEventHandler value)
   at WinDynamicDesktop.WallpaperEngine..ctor()
   at WinDynamicDesktop.AppContext..cctor()
   --- End of inner exception stack trace ---
   at WinDynamicDesktop.AppContext.InitializeTrayIcon()
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

[2024-01-19 14:32:04.196] System.DllNotFoundException: Dll was not found.
   at MS.Internal.WindowsBase.NativeMethodsSetLastError.SetWindowLongPtrWndProc(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
   at MS.Win32.UnsafeNativeMethods.CriticalSetWindowLong(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
   at MS.Win32.HwndSubclass.HookWindowProc(IntPtr hwnd, WndProc newWndProc, IntPtr oldWndProc)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

Are you using the Microsoft Store version of WDD?: No

**Comment by t1m0thyj** [comment]
Fixed in WinDD 5.6.1
