### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Dominiquini** [t1m0thyj/WinDynamicDesktop#562]
- WDD Version: 5.4.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Install new version over 5.3.1
2. Open the app
3. Crash

Are you using the Microsoft Store version of WDD?: No

Log:
```
[2024-02-15 15:49:26.479] System.Resources.MissingManifestResourceException: Could not find the resource "WinDynamicDesktop.ThemeDialog.resources" among the resources "WinDynamicDesktop.g.resources", "WinDynamicDesktop.Properties.Resources.resources", "WinDynamicDesktop.locale.am.mo", "WinDynamicDesktop.locale.ar-ae.mo", "WinDynamicDesktop.locale.ar.mo", "WinDynamicDesktop.locale.az.mo", "WinDynamicDesktop.locale.bg.mo", "WinDynamicDesktop.locale.bn.mo", "WinDynamicDesktop.locale.ca.mo", "WinDynamicDesktop.locale.cs.mo", ... embedded in the assembly "WinDynamicDesktop", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at WinDynamicDesktop.ThemeDialog.InitializeComponent()
   at WinDynamicDesktop.ThemeDialog..ctor()
   at WinDynamicDesktop.ThemeManager.SelectTheme()
   at WinDynamicDesktop.LaunchSequence.NextStep(Boolean themeReadyOverride)
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)
```

Log File:

[WinDynamicDesktop.exe.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/14298993/WinDynamicDesktop.exe.log)

**Comment by z1nc0r3** [comment]
Same on Windows 11 23H2

**Comment by Hexaae** [comment]
Confirmed, same here with Win11 23H2, was trying the MS Store edition:

![Immagine 2024-02-15 223454](https://github.com/t1m0thyj/WinDynamicDesktop/assets/8591462/a80f8f07-da59-4927-8620-877e504b2d37)

[WinDynamicDesktop.dll.log](https://github.com/t1m0thyj/WinDynamicDesktop/files/14302613/WinDynamicDesktop.dll.log)

**Comment by Housamelsherif** [comment]
I have the same issue. i installed it from here & from Microsoft store & the portable version all the same error

**Comment by t1m0thyj** [comment]
Sorry about this, in 5.4.0 I accidentally added a dependency on a resource file missing from the Release build. Since the resource file was present locally, I didn't catch then when testing the Debug build. Publishing a patch in a few minutes, and in the future will try to test releases in a clean environment to prevent this from happening again.

**Comment by t1m0thyj** [comment]
Fixed in 5.4.1
