### ISSUE TITLE
 new configuring schedule bug

### ISSUE THREAD

**Issue by gulk1** [t1m0thyj/WinDynamicDesktop#579]
- WDD Version: 5.4.2
- OS Version: W10 LTSC 21H2

Steps to Reproduce:

1. Start the program since daylight savings today.
2. Get an error.
3. Try to configure schedule via location name or window location

Are you using the Microsoft Store version of WDD?: No

Error:
`[2024-04-01 00:21:59.127] System.ArgumentException: The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid. (Parameter 'dateTime')
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, CachedData cachedData)
   at System.TimeZoneInfo.ConvertTime(DateTime dateTime, TimeZoneInfo destinationTimeZone)
   at WinDynamicDesktop.SunriseSunsetService.GetSunPhases(DateTime date, Double latitude, Double longitude)
   at WinDynamicDesktop.SunriseSunsetService.GetSolarData(DateTime date)
   at WinDynamicDesktop.SolarScheduler.CalcNextUpdateTime(SolarData data, DisplayEvent e)
   at WinDynamicDesktop.EventScheduler.Run(Boolean forceImageUpdate, DisplayEvent overrideEvent)
   at WinDynamicDesktop.ScheduleDialog.HandleScheduleChange()
   at WinDynamicDesktop.ScheduleDialog.okButton_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)`

**Comment by TheShark27** [comment]
Same here

**Comment by t1m0thyj** [comment]
This error only happens during the 0100-0200 hour on the day after the time changes. I've fixed it for next year in https://github.com/t1m0thyj/WinDynamicDesktop/commit/0903490c7aaa08739c0c348d79ad61d977546db5 😀

**Comment by gulk1** [comment]
> This error only happens during the 0100-0200 hour on the day after the time changes. I've fixed it for next year in [0903490](https://github.com/t1m0thyj/WinDynamicDesktop/commit/0903490c7aaa08739c0c348d79ad61d977546db5) 😀

aha.. I was wondering why it fixed itself a day later.

**Comment by t1m0thyj** [comment]
Fixed in WinDD 5.5.0
