### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by angerized** [t1m0thyj/WinDynamicDesktop#604]
On my work laptop, if I don't close the laptop lid when using the dual monitors, I get this error and the app crashes upon startup.

[2024-08-20 08:13:44.948] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WinDynamicDesktop.EventScheduler.Run(Boolean forceImageUpdate, DisplayEvent overrideEvent)
   at WinDynamicDesktop.AppContext..ctor(String[] args)
   at WinDynamicDesktop.Program.Main(String[] args)

- WDD Version: 5.5.0
- OS Version: W11 23H2

Steps to Reproduce:
 
1. Let the laptop lid open, thus having 3 monitors
2. Run WinDynamicDesktop.exe or reboot

Are you using the Microsoft Store version of WDD?: No

I'm in France, in case that matters somehow.

**Comment by t1m0thyj** [comment]
@angerized Thanks for reporting this! I think I've fixed the issue, could you try this test build to confirm? https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/10500057284

**Comment by t1m0thyj** [comment]
Fixed in WinDD 5.6.0
