### ISSUE TITLE
Error upon opening application (UWP version)

### ISSUE THREAD

**Issue by bacillusmet** [t1m0thyj/WinDynamicDesktop#95]
Hi,

After installing the most recent update (version 3.0.0) through the Microsoft Store I am encountering an error
![windynamicdesktop_error](https://user-images.githubusercontent.com/46751659/51254572-a62e6c00-19a1-11e9-97f8-435748be60b4.png)
 when trying to start the application.

I have deleted local files, reinstalled the app and restarted my computer, and the problem persists. I am running Windows 10 (Education edition, managed by IT department).

From the log file:

> 
System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at SunCalcNet.Utils.DateTimeUtils.FromJulian(Double j)
   at SunCalcNet.SunCalc.GetSunPhases(DateTime date, Double lat, Double lng)
   at WinDynamicDesktop.SunriseSunsetService.GetSunPhases(DateTime date, String lat, String lng)
   at WinDynamicDesktop.SunriseSunsetService.GetSolarData(DateTime date)
   at WinDynamicDesktop.WallpaperChangeScheduler.RunScheduler(Boolean forceImageUpdate)
   at WinDynamicDesktop.ThemeDialog.applyButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
System.ArgumentOutOfRangeException: Value to add was out of range.

The error does not appear until I try setting my location, after doing a fresh install.

**Comment by bacillusmet** [comment]
Hi,

That seems to have worked. I live in Trondheim, Norway, and changing the location to Oslo, Norway seems to have fixed it. Thank you!

**Comment by t1m0thyj** [comment]
Reopening this because the location should not matter, I believe this is a bug and want to investigate it further.

**Comment by FantasiaChan** [comment]
What do you use suncalc for?

**Comment by t1m0thyj** [comment]
@FantasiaChan WinDynamicDesktop uses the [SunCalc](https://github.com/kostebudinoski/SunCalc-Net) library to calculate the times of day when the sun is at specific angles. This is how the app knows which images to show when based on your location. You can see more specifically how it is used [here](https://github.com/t1m0thyj/WinDynamicDesktop/blob/master/src/SunriseSunset.cs) in the code.

**Comment by FantasiaChan** [comment]
uh. How about DateTime.Now?

**Comment by FantasiaChan** [comment]
(I recently reinstalled Windows and can't do anything now)

**Comment by bacillusmet** [comment]
It's most likely unrelated, but I can add that the experimental lock screen changer feature does not work for me either.

I am using the newest UWP version and have changed the settings.conf file setting to true. 

I also want to add that I just tried setting the location back to the original one, and it accepted the change without throwing any errors.

**Comment by t1m0thyj** [comment]
Closing this since the original issue was resolved and there is now a new issue to track problems with the experimental lock screen changer feature (#101).
